### PR TITLE
Revert "ADD AWS Settings in LMS "

### PR DESCRIPTION
**Pull request by rehan99000**
Reverts edly-io/edx-platform#204

**Description:**
These settings were making uploaded images inaccessible so we have to revert these changes.

image
image

### CODE REVIEW

**Review by asadmanzoor93 — APPROVED** [review]

**Review by zubair-arbi — APPROVED** [review]
LGTM 👍

**Comment by zubair-arbi** [comment]
Previously we have same issue with certificates template assets with URL like https://edly-prod-multisites-edx-storage.s3.amazonaws.com/certificate_template_assets/16/universitasx-custom-certificate-watermark.svg so we made the path `certificate_template_assets` on our buckets public. 

But now there are other paths and buckets which need to be public:
https://profile-images.edx-cdn.org/prod/00ae11684da43ad2fa436fa17a110adb_500.jpg?v=1614235632
https://edxuploads.s3.amazonaws.com/161423548763007395414.png

**Review by ziafazal — APPROVED** [review]
@rehan99000 @zubair-arbi. 
LGTM. Let's open edx uploads and profile image buckets for public. We need to create a separate bucket for private content like bulk enrollment CSVs.

**Comment by zubair-arbi** [comment]
@rehan99000 @ziafazal @rizwanghzzaal @zunairasid1231 @NIXKnight I have created a followup ticket to integrate and test the new private bucket: https://edlyio.atlassian.net/browse/EDLY-2657

**Pull request merged**
