### PR TITLE
Add user blocking feature - EDLY-3498

### PR DESCRIPTION
**Pull request by taimoor-ahmed-1**
**Description:** This PR adds `is_blocked` boolean in `EdlyUserProfile` model for user blocking feature.

**JIRA:** 
https://edlyio.atlassian.net/browse/EDLY-3498

**Related PR:**
https://github.com/edly-io/edly-panel-edx-app/pull/141

**Visible Changes:**
Screenshot 2021-08-23 at 6 09 54 PM

### CODE REVIEW

**Review by zubair-arbi — APPROVED** [review]
LGTM 👍

**Comment by ziafazal** [comment]
@taimoor-ahmed-1 where is the code which makes user's password unusable?

**Comment by taimoor-ahmed-1** [comment]
> @taimoor-ahmed-1 where is the code which makes user's password unusable?

@ziafazal here is the PR for it: https://github.com/edly-io/edly-panel-edx-app/pull/141

**Review by asadmanzoor93 — CHANGES_REQUESTED** [review]
Add unit tests for this model fiield.

**Comment by taimoor-ahmed-1** [comment]
> Add unit tests for this model fiield.

@asadmanzoor93 done.

**Review by asadmanzoor93 — APPROVED** [review]
LGTM 👍

**Pull request merged**
