### PR TITLE
Restricts course access if signed in user has different edx organization

### PR DESCRIPTION
**Pull request by rehan99000**
****Work in progress****
**Description:**
This change restricts viewing a course if a signed user has different edx organization than that of course being accessed.

image

### CODE REVIEW

**Comment by ziafazal** [comment]
@rehan99000 do we need this restriction with `CourseCreator` role?

**Comment by rehan99000** [comment]
> @rehan99000 do we need this restriction with `CourseCreator` role?

@ziafazal This condition is applied in `get_course_and_check_access` which is used in almost all the course and course-related handlers to get the required course. This would be applied no matter if a user is a course creator or a staff.
I am going to check this for cohorts and any other use case I can find but if this works like it is working, we can create both staff as well as Course creators as staff will not be able to access any course even by course ID and in turn, will not be able to manipulate that course in any way.

**Comment by ziafazal** [comment]
@rehan99000 we may be able to restrict staff users access by these changes in certain areas of studio buth staff users have special permissions all over edx platoform can we apply those check everywhere in LMS and ecommerce and credentails or any service we are going use? Even if we do I don't want to create a hug diff from upstream to avoid maintainance overhead.

**Comment by rehan99000** [comment]
> @rehan99000 we may be able to restrict staff users access by these changes in certain areas of studio buth staff users have special permissions all over edx platoform can we apply those check everywhere in LMS and ecommerce and credentails or any service we are going use? Even if we do I don't want to create a hug diff from upstream to avoid maintainance overhead.

@ziafazal I understand your point. ensuring 200% that *each and every* place where staff has access is checked would be a tedious task. This check alone in this file won't do that obviously. One more idea that I have which can be worked on is creating our custom role like the GlobalStaff which has more access than `CourseCreator` but not same as staff and use it in student app auth app method `get_user_permissions` (https://github.com/edly-io/edx-platform/blob/8d840e6f55862fbf86c9d4c2fce46e3073bc98e6/common/djangoapps/student/auth.py#L73) and `user_has_role` (https://github.com/edly-io/edx-platform/blob/8d840e6f55862fbf86c9d4c2fce46e3073bc98e6/common/djangoapps/student/auth.py#L44) which are used widely over LMS and studio. This way we would be able to provide wider access to our staff(not actual staff but an Edly staff) with changes in only one place.
What are your thoughts on this?

**Pull request closed without merging**
